### PR TITLE
fix phase date validation while closing challenge

### LINKED ISSUE #218: Error with Registration dates when closing tasks
If you attempt to close a task in Direct and the registration scheduled and end dates are NOT in the future, the app errors complaining that the start date can't be greater than the end date.

The error gets raised on this call:  https://github.com/appirio-tech/direct-app/blob/master/services/contest_service_facade/src/java/main/com/topcoder/service/facade/contest/ejb/ContestServiceFacadeBean.java#L9158

And then triggers the validator in the Phase class:

Caused by: java.lang.IllegalArgumentException: scheduledEndDate can not before scheduledStartDate
	at com.topcoder.project.phases.ProjectPhaseHelper.checkDateNotBefore(ProjectPhaseHelper.java:79
I believe this happens if you create the task, but then don't activate/close it right away.  However, I think we should generically check this case when closing tasks.  We probably need to update the logic for setting the dates.  Maybe if the reg dates are already set, we should not attempt to update them.

### PR DESCRIPTION
**Pull request by deedee**
Fix #218

### CODE REVIEW

File: services/contest_service_facade/src/java/main/com/topcoder/service/facade/contest/ejb/ContestServiceFacadeBean.java [hunk 1]
```diff
@@ -9145,44 +9145,25 @@ public void closeSoftwareContest(TCSubject tcSubject, long projectId, long winne
...
-                        phase.setScheduledStartDate(regStartDate);
-                        phase.setFixedStartDate(regStartDate);
-                        phase.setActualStartDate(regStartDate);
-                        phase.setScheduledEndDate(submissionEndDate);
-                        phase.setActualEndDate(submissionEndDate);
-                        phase.setLength(2 * length);
-                        phase.setPhaseStatus(PhaseStatus.CLOSED);
+                if (PROJECT_SUBMISSION_PHASE_NAME.equals(phase.getPhaseType().getName())) {
+                    if (phase.getPhaseStatus().getId() == PhaseStatus.OPEN.getId() && needToUpdate) {
+                        phase.setActualStartDate(new Date());
```
Comment (skyhit) [inline services/contest_service_facade/src/java/main/com/topcoder/service/facade/contest/ejb/ContestServiceFacadeBean.java]: @deedee if the submission phase is open, why we need to update the actual start date?

File: services/contest_service_facade/src/java/main/com/topcoder/service/facade/contest/ejb/ContestServiceFacadeBean.java [hunk 2]
```diff
@@ -9145,44 +9145,25 @@ public void closeSoftwareContest(TCSubject tcSubject, long projectId, long winne
...
-                        submissionPhase = phase;
-                    } else if (PROJECT_REGISTRATION_PHASE_NAME.equals(phase.getPhaseType().getName())) {
-                        phase.setScheduledStartDate(regStartDate);
-                        phase.setFixedStartDate(regStartDate);
-                        phase.setActualStartDate(regStartDate);
-                        phase.setScheduledEndDate(submissionEndDate);
-                        phase.setActualEndDate(submissionEndDate);
-                        phase.setLength(2 * length);
-                        phase.setPhaseStatus(PhaseStatus.CLOSED);
+                if (PROJECT_SUBMISSION_PHASE_NAME.equals(phase.getPhaseType().getName())) {
```
Comment (skyhit) [inline services/contest_service_facade/src/java/main/com/topcoder/service/facade/contest/ejb/ContestServiceFacadeBean.java]: @deedee let's ignore phase is already closed.

File: services/contest_service_facade/src/java/main/com/topcoder/service/facade/contest/ejb/ContestServiceFacadeBean.java (hunk 1 above)
Comment (deedee) [inline services/contest_service_facade/src/java/main/com/topcoder/service/facade/contest/ejb/ContestServiceFacadeBean.java]: Actually `PhaseStatus.OPEN.getId() && needToUpdate`mean the phase is scheduled. Please go through code before. It has been set to OPEN to make `uploadSubmission` works.

It's not necessary but imagine if the  phase schedule for the future. On complete challenge it will use schedule start date(which is future date) and actual end date(current date) if we didn't update it

Comment (skyhit) [inline services/contest_service_facade/src/java/main/com/topcoder/service/facade/contest/ejb/ContestServiceFacadeBean.java]: @deedee ok

File: services/contest_service_facade/src/java/main/com/topcoder/service/facade/contest/ejb/ContestServiceFacadeBean.java [hunk 3]
```diff
@@ -9106,15 +9106,19 @@ public void closeSoftwareContest(TCSubject tcSubject, long projectId, long winne
...
-            boolean needToUpdate = false;
+            boolean phaseNeedToUpdate = false;
+            boolean phaseHasClosed = false;
             //make sure we have submission phase is opened if not update it
             for (com.topcoder.project.phases.Phase phase : phases) {
                 if (PROJECT_SUBMISSION_PHASE_NAME.equals(phase.getPhaseType().getName())) {
                     if (phase.getPhaseStatus().getId() != PhaseStatus.OPEN.getId()) {
-                        needToUpdate = true;
+                        phaseNeedToUpdate = true;
+                        if (phase.getPhaseStatus().getId() == PhaseStatus.CLOSED.getId()){
```
Comment (skyhit) [inline services/contest_service_facade/src/java/main/com/topcoder/service/facade/contest/ejb/ContestServiceFacadeBean.java]: @deedee for closed, why we want to open it  again?

**Comment by skyhit** [comment]
@deedee why close it?

File: services/contest_service_facade/src/java/main/com/topcoder/service/facade/contest/ejb/ContestServiceFacadeBean.java (hunk 3 above)
Comment (deedee) [inline services/contest_service_facade/src/java/main/com/topcoder/service/facade/contest/ejb/ContestServiceFacadeBean.java]: submission phase need to be open to make upload submission work

**Comment by deedee** [comment]
re-open. Sorry
